### ISSUE TITLE
On removing BeeHaw from join-lemmy.org

### ISSUE THREAD

**Issue by vinoff** [LemmyNet/joinlemmy-site#190] opened 2023-06-18 09:11 UTC
As we all know by now, BeeHaw has chosen to defederate (see their post [here](https://beehaw.org/post/567170)) from roughly 32% of the accounts active in the last month in the lemmy-verse. This is a significant number!

Now, is join-lemmy a site whose goal is to recommend joining/running instances for the lemmy community? Or is it a site for recommending the use of the lemmy software? Because these 2 things are entirely different. If the former, then I make the argument that BeeHaw should be removed from the site. This is because BeeHaw has unilaterally decided to defederate a significant portion of the lemmy community. It broke the community in 2. It is, indeed, running the Lemmy software, but it should not be seen as an integral part of the Lemmy community.

Many people on reddit are throwing around this as the main reason as to why they are not joining the Lemmy community.

BeeHaw's decision to break the community is bad for the following reasons:

 1. **Loss of Network Effects**: The strength of any social platform lies in its network effects, which depend on the size and engagement of its user base. When a community splits, it diminishes the overall network effects and hampers the growth potential of the platform. With a smaller user base, there may be less content, fewer discussions, and decreased interaction, making the platform less appealing to newcomers.

 2. **Diluted Community Engagement**: A fragmented community leads to a divided user base, resulting in the dispersion of valuable content, discussions, and expertise. It becomes harder for users to find active communities and engage in meaningful interactions when the community is divided across different instances. This dilution of engagement can hamper the sense of community and discourage users from participating actively.

 3. **Reduced Diversity of Perspectives**: A larger, unified community brings together a diverse range of perspectives, experiences, and ideas. When the community splits, the opportunity for cross-pollination (pun not intended!) of ideas and the discovery of new viewpoints diminishes. This can lead to an echo chamber effect within the fragmented instances, limiting intellectual growth and stifling innovation.

 4. **Impaired Collaborative Efforts**: Fragmenting the Lemmy community hinders collaborative efforts and collective problem-solving. Large-scale community initiatives, such as developing new features, addressing issues, or improving the platform's overall experience, may suffer due to the divided user base. The pooling of resources, skills, and knowledge becomes more challenging when communities are scattered. This is specially true if people decide to join other platforms.

 5. **Weakened Attraction for New Users**: A fragmented community appears less vibrant and active to potential new users. When evaluating a platform, users often consider the size and engagement of the community as indicators of its vitality. The fragmentation of Lemmy's community discourages new users from joining, as they might perceive a lack of activity or a divided user base as signs of an unstable or declining platform.

 6. **Competitive Disadvantage**: The fragmentation of the Lemmy community puts the platform at a competitive disadvantage compared to centralized social media alternatives and other federated platforms. A smaller user base and divided community may make it harder to attract users away from established platforms, as they offer larger and more consolidated user communities.

-----

This could, however, not be a permanent decision. I think it should be done ASAP, as to not drive people into BeeHaw for the reasons I mentioned above. In the future, however, I think BeeHaw should be added again, with the added information that it only federates with X% of the community. But for now, we need userbase and joining any other instance is the way to go.

**Comment by Nutomic** [comment] 2023-06-20 11:47
Duplicate of https://github.com/LemmyNet/joinlemmy-site/issues/186

**Closed** 2023-10-18 17:27 UTC
